### PR TITLE
Adding support for kibana 6.8.x

### PR DESCRIPTION
**Pull request by pprad**
Adding support for Kibana 6.8.x

### CODE REVIEW

**Comment by vitoresende** [comment]
I've tried to use the files as you commited but didn't work for me :(

**Comment by pprad** [comment]
Hello vitoresende,
Thanks for reaching out ! Can you provide more information on this, so that
we can figure out. I had a chance to look at
https://github.com/vitoresende/ob-kb-funnel-6.8.zip. Changes made by me
were not present :( . Would be happy to assist :)

**Comment by vitoresende** [comment]
Thanks so much for your reply @pprad !!
You're right. I don't know when but somehow I didn't commited with your changes.
Now, the plugin was installed correctly. But, it broke Elastic, see below how the "Visualization" on Kibana is now. Do you know how can I fix it?
Thanks again for your help and time!
image

**Comment by vitoresende** [comment]
Thanks so much for your reply @pprad !!
You're right. I don't know when but somehow I didn't commited with your changes.
Now, the plugin was installed correctly. I deleted my previous post cause I forgot to remove one line (I was wrong again). Now, everything is ok.
Thanks again for your help and time!

**Pull request closed without merging**
